name: anavis
description: AnAVIS, blood means life.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  auto_size_text: ^2.1.0
  beauty_textfield: ^0.0.1
  animated_text_kit: ^1.3.1
  progress_indicator_button: ^0.0.3
  http: ^0.12.0+2
  provider: ^3.1.0+1
  flushbar: ^1.9.1
  date_format: ^1.0.8
  wave: ^0.0.8
  pull_to_refresh: ^1.5.7
  avatar_glow: ^1.1.0
  flutter_swiper: ^1.1.6
  badges: ^1.1.0
  flare_flutter: ^1.8.1
  flutter_speed_dial: ^1.2.5
  fl_chart: ^0.6.0
  flutter_calendar_carousel: ^1.4.10
  slimy_card: ^1.0.1
  datetime_picker_formfield: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo_homepage.png
    - assets/images/divider.png
    - assets/general/sad.flr

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
